# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-15 01:48
from __future__ import unicode_literals

from django.db import migrations


def seed(apps, schema_editor):
    #models
    Client = apps.get_model("shopsite", "Client")
    Product = apps.get_model("shopsite", "Product")
    Sale = apps.get_model("shopsite", "Sale")

    #clients
    client_jose = Client(name='Jose', slug='jose')
    client_jose.save()
    client_maria = Client(name='Maria', slug='maria')
    client_maria.save()
    client_chico = Client(name='Chico', slug='chico')
    client_chico.save()

    #products
    product_a = Product(description='BANANA', price=2.0, slug='banana')
    product_a.save()
    product_b = Product(description='ATA', price=2.0, slug='ata')
    product_b.save()
    product_c = Product(description='JACA', price=2.0, slug='jaca')
    product_c.save()

    #sales
    sale_a = Sale(seller='paula', product=product_a, client=client_jose, slug='a', created_on='2017-01-01 22:14:39')
    sale_a.save()
    sale_b = Sale(seller='joao', product=product_b, client=client_maria, slug='b', created_on='2017-01-03 22:14:30')
    sale_b.save()
    sale_c = Sale(seller='caio', product=product_c, client=client_chico, slug='c', created_on='2017-02-03 22:14:31')
    sale_c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shopsite', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed),
    ]
